services:

  pg:
    image: postgres
    environment:
      POSTGRES_DB: warehouse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5433:5432"

  fastapi-app:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - pg