version: '3.9'

services:
  warehouse-application:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: warehouse-application
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:123@db:5432/warehouse
    depends_on:
      - db
    volumes:
      - ./warehouse-application:/app/warehouse-application
    ports:
      - "8000:8000"
    networks:
      - warehouse
    # restart: always

  db:
    image: postgres:16
    container_name: warehouse-application-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./warehouse-application/.env
    ports:
      - "5433:5432"
    networks:
      - warehouse
    restart: always

volumes:
  postgres_data:

networks:
  warehouse: